# Site settings
title: POSC 3610
subtitle: International Conflict
description: |
    The onset, expansion and consequences of inter-state conflict lie at the heart of international relations scholarship. This class will explore these topics, highlighting what we know and what we do not know. We will start by clarifying our concepts and what we mean when we use terms like "dispute" and "war." We will then review scholarship on some classic concepts and "correlates" of inter-state conflict, like power, alliances, contiguity, and democracy. We will transition to a discussion of what we know about the consequences of conflict, like rivalry relationships, and conflict recurrence. We will conclude with a discussion of the frontier of the field, touching on newer topics like leaders in conflict and the nexus between climate change and conflict. Students that complete this class should have a broad overview of prominent quantitative scholarship on the cause of disputes and war in the international system, situating them in scholarship in the "peace science" field.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://posc3610.svmiller.com" # the base hostname & protocol for your site
syllabus: "http://posc3610.svmiller.com/syllabus/posc3610-spring2022-syllabus.pdf"
githubdir: "svmiller/posc3610"

# Author/user information
email: svmille@clemson.edu
twitter_username: stevenvmiller
github_username:  svmiller
authorurl: "http://svmiller.com"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
