# Site settings
title: POSC 3610
subtitle: International Conflict
description: |
    The onset, expansion and consequences of inter-state conflict lie at the heart of international relations scholarship.
      This class will explore these topics, highlighting what we know and what we do not know. 
      We will start by clarifying our concepts and what we mean when we use terms like "dispute" and "war." 
      The rest proceeds as an overview of the literature in the spirit of the Correlates of War project. 
      We will discuss the ubiquitous and problematic issue of "power" in international relations. 
      We will reiterate that most conflicts are between land-contiguous neighbors and concern territorial issues between them.
      Thereafter, we will discuss numerous other correlates of war and peace, like alliances, joint democracy, and rivalry.
        We will also talk about conflict processes like deterrence, compellence, dispute escalation and the dynamics of war.
         Students that complete this class should have a broad overview of prominent quantitative scholarship on the cause
          of disputes and war in the international system, situating them in scholarship in the "peace science" field.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://posc3610.svmiller.com" # the base hostname & protocol for your site
syllabus: "http://posc3610.svmiller.com/syllabus/posc3610-fall2019-syllabus.pdf"
githubdir: "svmiller/posc3610"

# Author/user information
email: svmille@clemson.edu
twitter_username: stevenvmiller
github_username:  svmiller
authorurl: "http://svmiller.com"
address: |
    Department of Political Science
    232 Brackett Hall
    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
